export const indianCities = [
  // Andhra Pradesh
  { name: "Visakhapatnam", state: "Andhra Pradesh" },
  { name: "Vijayawada", state: "Andhra Pradesh" },
  { name: "Guntur", state: "Andhra Pradesh" },
  { name: "Nellore", state: "Andhra Pradesh" },
  { name: "Kurnool", state: "Andhra Pradesh" },
  { name: "Rajahmundry", state: "Andhra Pradesh" },
  { name: "Tirupati", state: "Andhra Pradesh" },
  { name: "Kadapa", state: "Andhra Pradesh" },
  { name: "Anantapur", state: "Andhra Pradesh" },
  { name: "Chittoor", state: "Andhra Pradesh" },
  { name: "Eluru", state: "Andhra Pradesh" },
  { name: "Ongole", state: "Andhra Pradesh" },
  { name: "Machilipatnam", state: "Andhra Pradesh" },
  { name: "Hindupur", state: "Andhra Pradesh" },
  { name: "Srikakulam", state: "Andhra Pradesh" },

  // Arunachal Pradesh
  { name: "Itanagar", state: "Arunachal Pradesh" },
  { name: "Naharlagun", state: "Arunachal Pradesh" },
  { name: "Pasighat", state: "Arunachal Pradesh" },
  { name: "Tezpur", state: "Arunachal Pradesh" },
  { name: "Bomdila", state: "Arunachal Pradesh" },
  { name: "Ziro", state: "Arunachal Pradesh" },
  { name: "Along", state: "Arunachal Pradesh" },
  { name: "Tezu", state: "Arunachal Pradesh" },
  { name: "Changlang", state: "Arunachal Pradesh" },
  { name: "Khonsa", state: "Arunachal Pradesh" },

  // Assam
  { name: "Guwahati", state: "Assam" },
  { name: "Silchar", state: "Assam" },
  { name: "Dibrugarh", state: "Assam" },
  { name: "Jorhat", state: "Assam" },
  { name: "Nagaon", state: "Assam" },
  { name: "Tinsukia", state: "Assam" },
  { name: "Tezpur", state: "Assam" },
  { name: "Bongaigaon", state: "Assam" },
  { name: "Karimganj", state: "Assam" },
  { name: "Sivasagar", state: "Assam" },
  { name: "Goalpara", state: "Assam" },
  { name: "Diphu", state: "Assam" },
  { name: "North Lakhimpur", state: "Assam" },
  { name: "Mangaldoi", state: "Assam" },
  { name: "Haflong", state: "Assam" },

  // Bihar
  { name: "Patna", state: "Bihar" },
  { name: "Gaya", state: "Bihar" },
  { name: "Bhagalpur", state: "Bihar" },
  { name: "Muzaffarpur", state: "Bihar" },
  { name: "Purnia", state: "Bihar" },
  { name: "Darbhanga", state: "Bihar" },
  { name: "Bihar Sharif", state: "Bihar" },
  { name: "Arrah", state: "Bihar" },
  { name: "Begusarai", state: "Bihar" },
  { name: "Katihar", state: "Bihar" },
  { name: "Munger", state: "Bihar" },
  { name: "Chhapra", state: "Bihar" },
  { name: "Sasaram", state: "Bihar" },
  { name: "Hajipur", state: "Bihar" },
  { name: "Dehri", state: "Bihar" },
  { name: "Siwan", state: "Bihar" },
  { name: "Motihari", state: "Bihar" },
  { name: "Nawada", state: "Bihar" },
  { name: "Bagaha", state: "Bihar" },
  { name: "Buxar", state: "Bihar" },

  // Chhattisgarh
  { name: "Raipur", state: "Chhattisgarh" },
  { name: "Bhilai", state: "Chhattisgarh" },
  { name: "Bilaspur", state: "Chhattisgarh" },
  { name: "Korba", state: "Chhattisgarh" },
  { name: "Durg", state: "Chhattisgarh" },
  { name: "Rajnandgaon", state: "Chhattisgarh" },
  { name: "Jagdalpur", state: "Chhattisgarh" },
  { name: "Raigarh", state: "Chhattisgarh" },
  { name: "Ambikapur", state: "Chhattisgarh" },
  { name: "Mahasamund", state: "Chhattisgarh" },
  { name: "Dhamtari", state: "Chhattisgarh" },
  { name: "Chirmiri", state: "Chhattisgarh" },
  { name: "Janjgir", state: "Chhattisgarh" },
  { name: "Kanker", state: "Chhattisgarh" },
  { name: "Tilda", state: "Chhattisgarh" },

  // Goa
  { name: "Panaji", state: "Goa" },
  { name: "Vasco da Gama", state: "Goa" },
  { name: "Margao", state: "Goa" },
  { name: "Mapusa", state: "Goa" },
  { name: "Ponda", state: "Goa" },
  { name: "Bicholim", state: "Goa" },
  { name: "Curchorem", state: "Goa" },
  { name: "Sanquelim", state: "Goa" },
  { name: "Cuncolim", state: "Goa" },
  { name: "Quepem", state: "Goa" },

  // Gujarat
  { name: "Ahmedabad", state: "Gujarat" },
  { name: "Surat", state: "Gujarat" },
  { name: "Vadodara", state: "Gujarat" },
  { name: "Rajkot", state: "Gujarat" },
  { name: "Bhavnagar", state: "Gujarat" },
  { name: "Jamnagar", state: "Gujarat" },
  { name: "Junagadh", state: "Gujarat" },
  { name: "Gandhinagar", state: "Gujarat" },
  { name: "Anand", state: "Gujarat" },
  { name: "Navsari", state: "Gujarat" },
  { name: "Morbi", state: "Gujarat" },
  { name: "Nadiad", state: "Gujarat" },
  { name: "Surendranagar", state: "Gujarat" },
  { name: "Bharuch", state: "Gujarat" },
  { name: "Mehsana", state: "Gujarat" },
  { name: "Bhuj", state: "Gujarat" },
  { name: "Porbandar", state: "Gujarat" },
  { name: "Palanpur", state: "Gujarat" },
  { name: "Vapi", state: "Gujarat" },
  { name: "Godhra", state: "Gujarat" },

  // Haryana
  { name: "Faridabad", state: "Haryana" },
  { name: "Gurgaon", state: "Haryana" },
  { name: "Panipat", state: "Haryana" },
  { name: "Ambala", state: "Haryana" },
  { name: "Yamunanagar", state: "Haryana" },
  { name: "Rohtak", state: "Haryana" },
  { name: "Hisar", state: "Haryana" },
  { name: "Karnal", state: "Haryana" },
  { name: "Sonipat", state: "Haryana" },
  { name: "Panchkula", state: "Haryana" },
  { name: "Bhiwani", state: "Haryana" },
  { name: "Sirsa", state: "Haryana" },
  { name: "Jind", state: "Haryana" },
  { name: "Thanesar", state: "Haryana" },
  { name: "Kaithal", state: "Haryana" },
  { name: "Palwal", state: "Haryana" },
  { name: "Rewari", state: "Haryana" },
  { name: "Hansi", state: "Haryana" },
  { name: "Narnaul", state: "Haryana" },
  { name: "Fatehabad", state: "Haryana" },

  // Himachal Pradesh
  { name: "Shimla", state: "Himachal Pradesh" },
  { name: "Dharamshala", state: "Himachal Pradesh" },
  { name: "Solan", state: "Himachal Pradesh" },
  { name: "Mandi", state: "Himachal Pradesh" },
  { name: "Palampur", state: "Himachal Pradesh" },
  { name: "Baddi", state: "Himachal Pradesh" },
  { name: "Nahan", state: "Himachal Pradesh" },
  { name: "Paonta Sahib", state: "Himachal Pradesh" },
  { name: "Sundernagar", state: "Himachal Pradesh" },
  { name: "Chamba", state: "Himachal Pradesh" },
  { name: "Una", state: "Himachal Pradesh" },
  { name: "Kullu", state: "Himachal Pradesh" },
  { name: "Hamirpur", state: "Himachal Pradesh" },
  { name: "Bilaspur", state: "Himachal Pradesh" },
  { name: "Yol", state: "Himachal Pradesh" },

  // Jharkhand
  { name: "Ranchi", state: "Jharkhand" },
  { name: "Jamshedpur", state: "Jharkhand" },
  { name: "Dhanbad", state: "Jharkhand" },
  { name: "Bokaro", state: "Jharkhand" },
  { name: "Deoghar", state: "Jharkhand" },
  { name: "Phusro", state: "Jharkhand" },
  { name: "Hazaribagh", state: "Jharkhand" },
  { name: "Giridih", state: "Jharkhand" },
  { name: "Ramgarh", state: "Jharkhand" },
  { name: "Medininagar", state: "Jharkhand" },
  { name: "Chirkunda", state: "Jharkhand" },
  { name: "Pakaur", state: "Jharkhand" },
  { name: "Chaibasa", state: "Jharkhand" },
  { name: "Dumka", state: "Jharkhand" },
  { name: "Madhupur", state: "Jharkhand" },

  // Karnataka
  { name: "Bangalore", state: "Karnataka" },
  { name: "Mysore", state: "Karnataka" },
  { name: "Hubli", state: "Karnataka" },
  { name: "Mangalore", state: "Karnataka" },
  { name: "Belgaum", state: "Karnataka" },
  { name: "Gulbarga", state: "Karnataka" },
  { name: "Davanagere", state: "Karnataka" },
  { name: "Bellary", state: "Karnataka" },
  { name: "Bijapur", state: "Karnataka" },
  { name: "Shimoga", state: "Karnataka" },
  { name: "Tumkur", state: "Karnataka" },
  { name: "Raichur", state: "Karnataka" },
  { name: "Bidar", state: "Karnataka" },
  { name: "Hospet", state: "Karnataka" },
  { name: "Hassan", state: "Karnataka" },
  { name: "Bhadravati", state: "Karnataka" },
  { name: "Chitradurga", state: "Karnataka" },
  { name: "Udupi", state: "Karnataka" },
  { name: "Kolar", state: "Karnataka" },
  { name: "Mandya", state: "Karnataka" },

  // Kerala
  { name: "Thiruvananthapuram", state: "Kerala" },
  { name: "Kochi", state: "Kerala" },
  { name: "Kozhikode", state: "Kerala" },
  { name: "Kollam", state: "Kerala" },
  { name: "Thrissur", state: "Kerala" },
  { name: "Alappuzha", state: "Kerala" },
  { name: "Palakkad", state: "Kerala" },
  { name: "Kannur", state: "Kerala" },
  { name: "Kasaragod", state: "Kerala" },
  { name: "Kottayam", state: "Kerala" },
  { name: "Pathanamthitta", state: "Kerala" },
  { name: "Idukki", state: "Kerala" },
  { name: "Malappuram", state: "Kerala" },
  { name: "Wayanad", state: "Kerala" },
  { name: "Ernakulam", state: "Kerala" },

  // Madhya Pradesh
  { name: "Indore", state: "Madhya Pradesh" },
  { name: "Bhopal", state: "Madhya Pradesh" },
  { name: "Jabalpur", state: "Madhya Pradesh" },
  { name: "Gwalior", state: "Madhya Pradesh" },
  { name: "Ujjain", state: "Madhya Pradesh" },
  { name: "Sagar", state: "Madhya Pradesh" },
  { name: "Dewas", state: "Madhya Pradesh" },
  { name: "Satna", state: "Madhya Pradesh" },
  { name: "Ratlam", state: "Madhya Pradesh" },
  { name: "Rewa", state: "Madhya Pradesh" },
  { name: "Murwara", state: "Madhya Pradesh" },
  { name: "Singrauli", state: "Madhya Pradesh" },
  { name: "Burhanpur", state: "Madhya Pradesh" },
  { name: "Khandwa", state: "Madhya Pradesh" },
  { name: "Bhind", state: "Madhya Pradesh" },
  { name: "Chhindwara", state: "Madhya Pradesh" },
  { name: "Guna", state: "Madhya Pradesh" },
  { name: "Shivpuri", state: "Madhya Pradesh" },
  { name: "Vidisha", state: "Madhya Pradesh" },
  { name: "Chhatarpur", state: "Madhya Pradesh" },

  // Maharashtra
  { name: "Mumbai", state: "Maharashtra" },
  { name: "Pune", state: "Maharashtra" },
  { name: "Nagpur", state: "Maharashtra" },
  { name: "Thane", state: "Maharashtra" },
  { name: "Nashik", state: "Maharashtra" },
  { name: "Aurangabad", state: "Maharashtra" },
  { name: "Solapur", state: "Maharashtra" },
  { name: "Amravati", state: "Maharashtra" },
  { name: "Kolhapur", state: "Maharashtra" },
  { name: "Sangli", state: "Maharashtra" },
  { name: "Malegaon", state: "Maharashtra" },
  { name: "Akola", state: "Maharashtra" },
  { name: "Latur", state: "Maharashtra" },
  { name: "Dhule", state: "Maharashtra" },
  { name: "Ahmednagar", state: "Maharashtra" },
  { name: "Chandrapur", state: "Maharashtra" },
  { name: "Parbhani", state: "Maharashtra" },
  { name: "Jalgaon", state: "Maharashtra" },
  { name: "Bhusawal", state: "Maharashtra" },
  { name: "Nanded", state: "Maharashtra" },

  // Manipur
  { name: "Imphal", state: "Manipur" },
  { name: "Thoubal", state: "Manipur" },
  { name: "Lilong", state: "Manipur" },
  { name: "Mayang Imphal", state: "Manipur" },
  { name: "Kakching", state: "Manipur" },
  { name: "Bishnupur", state: "Manipur" },
  { name: "Churachandpur", state: "Manipur" },
  { name: "Senapati", state: "Manipur" },
  { name: "Ukhrul", state: "Manipur" },
  { name: "Tamenglong", state: "Manipur" },

  // Meghalaya
  { name: "Shillong", state: "Meghalaya" },
  { name: "Tura", state: "Meghalaya" },
  { name: "Nongstoin", state: "Meghalaya" },
  { name: "Jowai", state: "Meghalaya" },
  { name: "Baghmara", state: "Meghalaya" },
  { name: "Williamnagar", state: "Meghalaya" },
  { name: "Resubelpara", state: "Meghalaya" },
  { name: "Mawkyrwat", state: "Meghalaya" },
  { name: "Ampati", state: "Meghalaya" },
  { name: "Mairang", state: "Meghalaya" },

  // Mizoram
  { name: "Aizawl", state: "Mizoram" },
  { name: "Lunglei", state: "Mizoram" },
  { name: "Saiha", state: "Mizoram" },
  { name: "Champhai", state: "Mizoram" },
  { name: "Kolasib", state: "Mizoram" },
  { name: "Lawngtlai", state: "Mizoram" },
  { name: "Mamit", state: "Mizoram" },
  { name: "Serchhip", state: "Mizoram" },
  { name: "Khawzawl", state: "Mizoram" },
  { name: "Hnahthial", state: "Mizoram" },

  // Nagaland
  { name: "Kohima", state: "Nagaland" },
  { name: "Dimapur", state: "Nagaland" },
  { name: "Mokokchung", state: "Nagaland" },
  { name: "Tuensang", state: "Nagaland" },
  { name: "Wokha", state: "Nagaland" },
  { name: "Zunheboto", state: "Nagaland" },
  { name: "Phek", state: "Nagaland" },
  { name: "Kiphire", state: "Nagaland" },
  { name: "Longleng", state: "Nagaland" },
  { name: "Peren", state: "Nagaland" },
  { name: "Mon", state: "Nagaland" },
  { name: "Noklak", state: "Nagaland" },

  // Odisha
  { name: "Bhubaneswar", state: "Odisha" },
  { name: "Cuttack", state: "Odisha" },
  { name: "Rourkela", state: "Odisha" },
  { name: "Berhampur", state: "Odisha" },
  { name: "Sambalpur", state: "Odisha" },
  { name: "Puri", state: "Odisha" },
  { name: "Balasore", state: "Odisha" },
  { name: "Bhadrak", state: "Odisha" },
  { name: "Baripada", state: "Odisha" },
  { name: "Jharsuguda", state: "Odisha" },
  { name: "Jeypore", state: "Odisha" },
  { name: "Barbil", state: "Odisha" },
  { name: "Khordha", state: "Odisha" },
  { name: "Rayagada", state: "Odisha" },
  { name: "Koraput", state: "Odisha" },

  // Punjab
  { name: "Ludhiana", state: "Punjab" },
  { name: "Amritsar", state: "Punjab" },
  { name: "Jalandhar", state: "Punjab" },
  { name: "Patiala", state: "Punjab" },
  { name: "Bathinda", state: "Punjab" },
  { name: "Mohali", state: "Punjab" },
  { name: "Firozpur", state: "Punjab" },
  { name: "Batala", state: "Punjab" },
  { name: "Pathankot", state: "Punjab" },
  { name: "Moga", state: "Punjab" },
  { name: "Abohar", state: "Punjab" },
  { name: "Malerkotla", state: "Punjab" },
  { name: "Khanna", state: "Punjab" },
  { name: "Phagwara", state: "Punjab" },
  { name: "Muktsar", state: "Punjab" },
  { name: "Barnala", state: "Punjab" },
  { name: "Rajpura", state: "Punjab" },
  { name: "Hoshiarpur", state: "Punjab" },
  { name: "Kapurthala", state: "Punjab" },
  { name: "Faridkot", state: "Punjab" },

  // Rajasthan
  { name: "Jaipur", state: "Rajasthan" },
  { name: "Jodhpur", state: "Rajasthan" },
  { name: "Kota", state: "Rajasthan" },
  { name: "Bikaner", state: "Rajasthan" },
  { name: "Udaipur", state: "Rajasthan" },
  { name: "Ajmer", state: "Rajasthan" },
  { name: "Bhilwara", state: "Rajasthan" },
  { name: "Alwar", state: "Rajasthan" },
  { name: "Bharatpur", state: "Rajasthan" },
  { name: "Pali", state: "Rajasthan" },
  { name: "Barmer", state: "Rajasthan" },
  { name: "Sikar", state: "Rajasthan" },
  { name: "Tonk", state: "Rajasthan" },
  { name: "Kishangarh", state: "Rajasthan" },
  { name: "Beawar", state: "Rajasthan" },
  { name: "Hanumangarh", state: "Rajasthan" },
  { name: "Sri Ganganagar", state: "Rajasthan" },
  { name: "Jaisalmer", state: "Rajasthan" },
  { name: "Churu", state: "Rajasthan" },
  { name: "Jhunjhunu", state: "Rajasthan" },

  // Sikkim
  { name: "Gangtok", state: "Sikkim" },
  { name: "Namchi", state: "Sikkim" },
  { name: "Geyzing", state: "Sikkim" },
  { name: "Mangan", state: "Sikkim" },
  { name: "Jorethang", state: "Sikkim" },
  { name: "Nayabazar", state: "Sikkim" },
  { name: "Rangpo", state: "Sikkim" },
  { name: "Singtam", state: "Sikkim" },
  { name: "Yuksom", state: "Sikkim" },
  { name: "Pelling", state: "Sikkim" },

  // Tamil Nadu
  { name: "Chennai", state: "Tamil Nadu" },
  { name: "Coimbatore", state: "Tamil Nadu" },
  { name: "Madurai", state: "Tamil Nadu" },
  { name: "Tiruchirappalli", state: "Tamil Nadu" },
  { name: "Salem", state: "Tamil Nadu" },
  { name: "Tirunelveli", state: "Tamil Nadu" },
  { name: "Tiruppur", state: "Tamil Nadu" },
  { name: "Vellore", state: "Tamil Nadu" },
  { name: "Erode", state: "Tamil Nadu" },
  { name: "Thoothukkudi", state: "Tamil Nadu" },
  { name: "Dindigul", state: "Tamil Nadu" },
  { name: "Thanjavur", state: "Tamil Nadu" },
  { name: "Ranipet", state: "Tamil Nadu" },
  { name: "Sivakasi", state: "Tamil Nadu" },
  { name: "Karur", state: "Tamil Nadu" },
  { name: "Udhagamandalam", state: "Tamil Nadu" },
  { name: "Hosur", state: "Tamil Nadu" },
  { name: "Nagercoil", state: "Tamil Nadu" },
  { name: "Kanchipuram", state: "Tamil Nadu" },
  { name: "Kumarakonam", state: "Tamil Nadu" },

  // Telangana
  { name: "Hyderabad", state: "Telangana" },
  { name: "Warangal", state: "Telangana" },
  { name: "Nizamabad", state: "Telangana" },
  { name: "Khammam", state: "Telangana" },
  { name: "Karimnagar", state: "Telangana" },
  { name: "Ramagundam", state: "Telangana" },
  { name: "Mahabubnagar", state: "Telangana" },
  { name: "Nalgonda", state: "Telangana" },
  { name: "Adilabad", state: "Telangana" },
  { name: "Suryapet", state: "Telangana" },
  { name: "Miryalaguda", state: "Telangana" },
  { name: "Jagtial", state: "Telangana" },
  { name: "Mancherial", state: "Telangana" },
  { name: "Kamareddy", state: "Telangana" },
  { name: "Siddipet", state: "Telangana" },

  // Tripura
  { name: "Agartala", state: "Tripura" },
  { name: "Dharmanagar", state: "Tripura" },
  { name: "Udaipur", state: "Tripura" },
  { name: "Kailasahar", state: "Tripura" },
  { name: "Belonia", state: "Tripura" },
  { name: "Khowai", state: "Tripura" },
  { name: "Ambassa", state: "Tripura" },
  { name: "Ranir Bazar", state: "Tripura" },
  { name: "Sonamura", state: "Tripura" },
  { name: "Kumarghat", state: "Tripura" },

  // Uttar Pradesh
  { name: "Lucknow", state: "Uttar Pradesh" },
  { name: "Kanpur", state: "Uttar Pradesh" },
  { name: "Ghaziabad", state: "Uttar Pradesh" },
  { name: "Agra", state: "Uttar Pradesh" },
  { name: "Varanasi", state: "Uttar Pradesh" },
  { name: "Meerut", state: "Uttar Pradesh" },
  { name: "Allahabad", state: "Uttar Pradesh" },
  { name: "Bareilly", state: "Uttar Pradesh" },
  { name: "Aligarh", state: "Uttar Pradesh" },
  { name: "Moradabad", state: "Uttar Pradesh" },
  { name: "Saharanpur", state: "Uttar Pradesh" },
  { name: "Gorakhpur", state: "Uttar Pradesh" },
  { name: "Firozabad", state: "Uttar Pradesh" },
  { name: "Jhansi", state: "Uttar Pradesh" },
  { name: "Muzaffarnagar", state: "Uttar Pradesh" },
  { name: "Mathura", state: "Uttar Pradesh" },
  { name: "Rampur", state: "Uttar Pradesh" },
  { name: "Shahjahanpur", state: "Uttar Pradesh" },
  { name: "Farrukhabad", state: "Uttar Pradesh" },
  { name: "Mau", state: "Uttar Pradesh" },
  { name: "Hapur", state: "Uttar Pradesh" },
  { name: "Noida", state: "Uttar Pradesh" },
  { name: "Etawah", state: "Uttar Pradesh" },
  { name: "Mirzapur", state: "Uttar Pradesh" },
  { name: "Bulandshahr", state: "Uttar Pradesh" },

  // Uttarakhand
  { name: "Dehradun", state: "Uttarakhand" },
  { name: "Haridwar", state: "Uttarakhand" },
  { name: "Roorkee", state: "Uttarakhand" },
  { name: "Haldwani", state: "Uttarakhand" },
  { name: "Rudrapur", state: "Uttarakhand" },
  { name: "Kashipur", state: "Uttarakhand" },
  { name: "Rishikesh", state: "Uttarakhand" },
  { name: "Ramnagar", state: "Uttarakhand" },
  { name: "Pithoragarh", state: "Uttarakhand" },
  { name: "Jaspur", state: "Uttarakhand" },
  { name: "Almora", state: "Uttarakhand" },
  { name: "Mussoorie", state: "Uttarakhand" },
  { name: "Nainital", state: "Uttarakhand" },
  { name: "Bageshwar", state: "Uttarakhand" },
  { name: "Champawat", state: "Uttarakhand" },

  // West Bengal
  { name: "Kolkata", state: "West Bengal" },
  { name: "Howrah", state: "West Bengal" },
  { name: "Durgapur", state: "West Bengal" },
  { name: "Asansol", state: "West Bengal" },
  { name: "Siliguri", state: "West Bengal" },
  { name: "Malda", state: "West Bengal" },
  { name: "Baharampur", state: "West Bengal" },
  { name: "Habra", state: "West Bengal" },
  { name: "Kharagpur", state: "West Bengal" },
  { name: "Shantipur", state: "West Bengal" },
  { name: "Dankuni", state: "West Bengal" },
  { name: "Dhulian", state: "West Bengal" },
  { name: "Ranaghat", state: "West Bengal" },
  { name: "Haldia", state: "West Bengal" },
  { name: "Raiganj", state: "West Bengal" },
  { name: "Krishnanagar", state: "West Bengal" },
  { name: "Nabadwip", state: "West Bengal" },
  { name: "Medinipur", state: "West Bengal" },
  { name: "Jalpaiguri", state: "West Bengal" },
  { name: "Balurghat", state: "West Bengal" },
]
